import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const robotoRegular = localFont({
  src: "./fonts/Roboto-Regular.woff",
  variable: "--font-roboto-regular",
  weight: "100 900",
});


export const metadata: Metadata = {
  title: "S&P MERVAL",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${robotoRegular.variable}`}>
        {children}
      </body>
    </html>
  );
}
